name: Deploy
on:
  push: 
    branches:
      - 'main'
  workflow_dispatch:

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


jobs:
  deploy-production-us-east-1:
    runs-on: ubuntu-latest
    
    env:
      ENVIRONMENT: production
      REGION: us-east-1

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup AWS credentials
      run: |
        export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
        export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        export AWS_DEFAULT_REGION=$REGION

    - name: Install CDK for python
      run: |
        python -m pip install aws-cdk-lib

    - name: Show diff
      run: |
        cdk diff -c env=$ENVIRONMENT
    
    - name: Synthesize
      run:
        cdk synth -c env=$ENVIRONMENT

    - name: Deploy
      run:
        cdk deploy -c env=$ENVIRONMENT