# lol do not use this in production
# this is so I can save on AWS costs


name: Multi-Region Destroy
on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS region'
        required: true
        default: 'us-east-1'
      environment:
        description: 'Environment to destroy'
        required: true
        type: choice
        options:
        - staging
        - production

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: setup-cdk
      uses: ./.github/actions/setup
      with:
        region: ${{ inputs.region }}
        environment: ${{ inputs.environment }}
        aws-access-key: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Get allow IP for bastion
      shell: bash
      id: ip
      run: | 
        ip=$(aws ssm get-parameter --region us-east-1 --with-decryption --name /bastion/allow-ip | jq -r '.Parameter.Value')
        echo "::set-output name=ip::$ip"

    - name: destroy
      run: cdk destroy --force -c env=${{ inputs.environment }} -c ip=${{ steps.ip.outputs.ip }} --require-approval never